# Generated by Django 4.0.6 on 2022-09-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255, unique=True)),
                ('desc', models.TextField(max_length=255)),
                ('date_posted', models.DateField(max_length=255)),
            ],
            options={
                'ordering': ['date_posted'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255, unique=True)),
                ('desc', models.TextField(max_length=255)),
                ('image', models.FileField(upload_to='news_uoloads')),
                ('date_posted', models.DateField()),
            ],
            options={
                'ordering': ['date_posted'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255, unique=True)),
                ('desc', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='Product_uoloads')),
                ('oldPrice', models.IntegerField(max_length=10)),
                ('newprice', models.IntegerField(max_length=10)),
                ('discount', models.IntegerField(max_length=20)),
            ],
            options={
                'ordering': ['discount'],
            },
        ),
    ]
