# Generated by Django 4.0.6 on 2022-09-30 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Jobs',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
