# Generated by Django 4.0.6 on 2022-09-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_products', '0002_alter_product_discount_alter_product_newprice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255, unique=True)),
                ('desc', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='Product_uoloads')),
            ],
            options={
                'ordering': ['Title'],
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255, unique=True)),
                ('desc', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='music_uploads')),
                ('Author', models.CharField(max_length=255)),
                ('Author_image', models.FileField(upload_to='Author_uploads')),
            ],
            options={
                'ordering': ['Title'],
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
