# Generated by Django 4.0.6 on 2022-09-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_products', '0004_alter_jobs_date_posted_alter_news_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date_posted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
