# Generated by Django 4.0.6 on 2022-09-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_products', '0007_alter_news_headline_alter_news_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.FileField(max_length=255, upload_to='news_uoloads'),
        ),
    ]
