# Generated by Django 4.0.6 on 2022-09-26 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_products', '0009_book_delete_movie_delete_music_alter_news_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
