# Generated by Django 4.0.6 on 2022-09-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_products', '0010_delete_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('image', models.URLField(max_length=255)),
                ('date_posted', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date_posted'],
            },
        ),
    ]
