# Generated by Django 4.0.6 on 2022-09-27 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_products', '0012_rename_desc_book_price_alter_jobs_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
