# Generated by Django 4.0.6 on 2022-09-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_products', '0013_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('image', models.URLField(max_length=255)),
                ('star', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
