# Generated by Django 4.0.6 on 2022-09-27 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_products', '0014_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='star',
        ),
    ]
