# Generated by Django 4.0.6 on 2022-09-27 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_products', '0015_remove_book_star'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
    ]
