# Generated by Django 4.0.6 on 2022-09-27 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_products', '0016_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
    ]
