# Generated by Django 4.0.6 on 2022-09-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_products', '0017_alter_book_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
