# Generated by Django 4.0.6 on 2022-09-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_products', '0018_jobs_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='date_posted',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='desc',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
