# Generated by Django 4.0.6 on 2022-09-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_products', '0019_jobs_company_alter_jobs_date_posted_alter_jobs_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='date_posted',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
