# Generated by Django 4.0.6 on 2022-09-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_products', '0021_alter_jobs_options_remove_jobs_date_posted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobs',
            options={'ordering': ['date_posted']},
        ),
        migrations.AddField(
            model_name='jobs',
            name='date_posted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
